In [1]:
import pickle
import numpy as np
import pandas as pd
import scipy.sparse as sp

from scipy.io import loadmat

In [ ]:
drug_features = loadmat('data/data_1/drugFeatureVectors.mat')
target_features = loadmat('data/data_1/targetFeatureVectors.mat')
interactions = loadmat('data/data_1/interactionMatrix.mat')

u_feat = drug_features['drugFeatureVectors']
v_feat = target_features['targetFeatureVectors']
y = interactions['Y']

In [ ]:
num_u = u_feat.shape[0]
num_v = v_feat.shape[0]

u_feat = sp.csr_matrix(u_feat)
v_feat = sp.csr_matrix(v_feat)

In [ ]:
neg_u, neg_v = np.where(y == 0)
neg_y = np.zeros(neg_u.shape)

pos_u, pos_v = np.where(y == 1)
pos_y = np.ones(pos_u.shape)

neg_set = np.vstack([neg_u, neg_v, neg_y])
pos_set = np.vstack([pos_u, pos_v, pos_y])

data = np.concatenate([pos_set, neg_set], axis=1).astype(np.int64)
u_nodes, v_nodes, ratings = data

In [ ]:
data

In [ ]:
u_nodes

In [ ]:
v_nodes

In [ ]:
ratings

In [ ]:
store_obj = (num_u, num_v, u_nodes, v_nodes, ratings, u_feat, v_feat)
with open('data/data_1/data_1.pkl', 'w') as f:
    pickle.dump(store_obj, f)

In [ ]:
f = open('data/data_2/drugFeatureVectors.txt')

In [ ]:
data = []
lines = f.readlines()

for line in lines:
    line = np.array(line.strip().split('\t')).astype(np.int64)
    data.append(line)
    
data = np.vstack(data)

In [ ]:
data.shape

In [ ]:
f.close()

In [2]:
def load_data_from_txt(data_path):
    with open(data_path) as f:
        data = []
        lines = f.readlines()

        for line in lines:
            line = np.array(line.strip().split('\t')).astype(np.int64)
            data.append(line)

        data = np.vstack(data)
        
    return data

In [3]:
u_feat = load_data_from_txt('data/data_2/drugFeatureVectors.txt')
v_feat = load_data_from_txt('data/data_2/targetFeatureVectors.txt')
y = load_data_from_txt('data/data_2/interactionMatrix.txt')

In [4]:
u_feat

array([[1, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])

In [5]:
v_feat

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [6]:
y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [7]:
num_u = u_feat.shape[0]
num_v = v_feat.shape[0]

u_feat = sp.csr_matrix(u_feat)
v_feat = sp.csr_matrix(v_feat)

In [8]:
u_feat, v_feat, num_u, num_v

(<1862x881 sparse matrix of type '<type 'numpy.int64'>'
 	with 218294 stored elements in Compressed Sparse Row format>,
 <1554x876 sparse matrix of type '<type 'numpy.int64'>'
 	with 2344 stored elements in Compressed Sparse Row format>,
 1862,
 1554)

In [9]:
neg_u, neg_v = np.where(y == 0)
neg_y = np.zeros(neg_u.shape)

pos_u, pos_v = np.where(y == 1)
pos_y = np.ones(pos_u.shape)

In [10]:
neg_set = np.vstack([neg_u, neg_v, neg_y])
pos_set = np.vstack([pos_u, pos_v, pos_y])

data = np.concatenate([pos_set, neg_set], axis=1).astype(np.int64)
u_nodes, v_nodes, ratings = data

In [12]:
data.shape

(3, 2893548)

In [13]:
pos_set

array([[0.000e+00, 1.000e+00, 2.000e+00, ..., 1.860e+03, 1.860e+03,
        1.861e+03],
       [7.090e+02, 3.910e+02, 1.125e+03, ..., 1.260e+02, 1.541e+03,
        4.770e+02],
       [1.000e+00, 1.000e+00, 1.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00]])

In [14]:
pos_set.shape

(3, 4809)

In [15]:
neg_set

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 1.861e+03, 1.861e+03,
        1.861e+03],
       [0.000e+00, 1.000e+00, 2.000e+00, ..., 1.551e+03, 1.552e+03,
        1.553e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [16]:
neg_set.shape

(3, 2888739)

In [21]:
u_nodes.shape

(2893548,)

In [22]:
v_nodes.shape

(2893548,)

In [20]:
ratings.shape

(2893548,)

In [23]:
store_obj = (num_u, num_v, u_nodes, v_nodes, ratings, u_feat, v_feat)
with open('data/data_2/data_2.pkl', 'w') as f:
    pickle.dump(store_obj, f)